export const clerkAppearance = {
  layout: {
    logoPlacement: 'none' as const,
    socialButtonsPlacement: 'top' as const,
  },
  variables: {
    colorPrimary: 'oklch(0.4 0.1 265)',
    colorBackground: 'oklch(0.995 0.004 70)',
    colorInputBackground: 'oklch(0.995 0.004 70)',
    colorText: 'oklch(0.22 0.015 70)',
    colorTextSecondary: 'oklch(0.5 0.01 70)',
    colorInputText: 'oklch(0.22 0.015 70)',
    colorDanger: 'oklch(0.42 0.11 75)',
    colorSuccess: 'oklch(0.32 0.09 150)',
    fontFamily: 'var(--font-plex-sans)',
    borderRadius: '6px',
    spacingUnit: '0.95rem',
  },
  elements: {
    rootBox: 'w-full',
    card: 'shadow-none border border-[oklch(0.85_0.015_70)] rounded-[6px] bg-[oklch(0.995_0.004_70)] p-6',
    headerTitle: 'font-serif text-2xl font-semibold',
    headerSubtitle: 'text-sm',
    socialButtonsBlockButton: 'border border-[oklch(0.85_0.015_70)] rounded-[6px] font-semibold text-sm',
    socialButtonsBlockButtonText: 'font-semibold text-sm',
    dividerLine: 'bg-[oklch(0.85_0.015_70)]',
    dividerText: 'text-xs uppercase tracking-wide',
    formFieldLabel: 'text-sm font-semibold',
    formFieldInput: 'border border-[oklch(0.85_0.015_70)] rounded-[6px] text-sm',
    formButtonPrimary: 'rounded-[6px] font-semibold text-sm normal-case shadow-none',
    footerActionText: 'text-sm',
    footerActionLink: 'font-semibold',
    identityPreviewEditButton: 'text-[oklch(0.4_0.1_265)]',
  },
}
